### ISSUE TITLE
update ? 

### ISSUE THREAD

**Issue by fas3r** [kelyvin/express-env-example#2]
Hello, 

following your update in march, do you know when you will publish your new version ? 

Thanks.

**Comment by kelyvin** [comment]
Hi @fas3r, 

Sorry for the delay. My open source & side projects have fallen behind because I've been wrapped up with other priorities. I'm going to try to recommit several hours on Sunday's to play some catch up. With that said, at this point I feel pretty good about the updated architecture (since I've been working in it extensively for the past four months). I just need clean it up to make it more *digestable* for others. I need to update a different project first today, so I may be able to get to this probably not the next Sunday, but the Sunday after.

Eta-ish around the end of the month? Please check back again if I don't post an update by then. 

Thanks!

**Comment by fas3r** [comment]
Hello @kelyvin , 

Thanks for your feedback. Sure I will check that you can be sure, I just wanted to know if it would come alive :).

Thanks !

**Comment by henrikra** [comment]
This is great news! @kelyvin

**Comment by ghost** [comment]
Hello m8, i've just cloned your project and tried to start it with npm but it seems that there is an error.
```
λ npm start

> express-env-sample@1.0.0 start C:\laragon\www\express-env-example
> node index.js

module.js:538
    throw err;
    ^

Error: Cannot find module 'express-handlebars'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\laragon\www\express-env-example\server\index.js:5:25)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-env-sample@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-env-sample@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Natan\AppData\Roaming\npm-cache\_logs\2018-09-25T13_38_01_218Z-debug.log
```

Do you know where it can come from and how to resolve it ?

**Comment by kelyvin** [comment]
@Natizyskunk Have you tried running `npm install` first to install all your dependencies? 

In order to run any Node.js app you'll need to make sure your dependencies are installed before running it. Usually to overcome this I tend to include an install command as part of `npm start`, but since this was an example project I didn't do it here. Let me know if that addresses your issue

**Comment by ghost** [comment]
My bad i should have known that this doesn't work this way and that i needed to do the `npm install` command before anything else ^^.
It has definitely resolve my problems, thx :)

**Comment by eddiemonge** [comment]
How is the update going?

**Comment by kelyvin** [comment]
Sorry I totally dropped the ball on this. You've all been very patient. 

I have blocked time off my calendar to get to it this week. My new goal is to have the code ready by the end of this month. Thanks for waiting and I'd like to ask if you can hold out just a tad bit longer. I promise the code will have some advanced stuff!

**Comment by malek-itani** [comment]
hello @kelyvin ,
thanks for structuring the server in a great way!
i have a question, when you are going to add **graphql** 
so that server supports both  ( router and graphql )

**Comment by JVGH** [comment]
Hi kelyvin, this is a great guide for newbs. Thank you! Did you get a chance to update this repo?

**Comment by kelyvin** [comment]
Hi @malek-itani - Sorry for not responding, didn't see this message. I don't have any immediate plans to add graphql support, but if I do I'll be sure to let you know. 

Hi @JVGH - Thanks for the kind words. Unfortunately, I've been unable to update this repo as I've been focused on other priorities right now. As a result, I've taken a temporary hiatus from my projects/blog. Hopefully, I'll be able to get to it sometime in the year when my main priorities have relaxed a bit, but that won't be for a while. :(

For everyone else, if you have any questions or would like any other tips to help improve your express setup (middleware, environment management, etc), please feel free to ask - answering questions and providing small blocks of code is no problem at all.

**Comment by nuri-engin** [comment]
@kelyvin Hello and thanks for that great work!

Wondering if any new update will show up and if it will! Is there any chance to see a way of handling DB connection with that very well handled project? 

A usage sample for the MongoDB or any other equivalent DB. Thus achieve a better architect with DB actions etc?

Thanks in advance.

**Comment by slidenerd** [comment]
so what is the status now
